/** Generated by scripts/fetch-horizons-trajectories.mjs. Do not hand edit. */
export type HorizonsMissionId = 'voyager1' | 'voyager2' | 'pioneer10' | 'newhorizons' | 'cassini' | 'galileo' | 'dawn' | 'rosetta' | 'osirisrex' | 'lucy' | 'psyche' | 'europaclipper'
export type HorizonsVectorSample = readonly [jdTdb: number, xAu: number, yAu: number, zAu: number, vxAuPerDay: number, vyAuPerDay: number, vzAuPerDay: number]
export type HorizonsTrajectoryAsset = {
  readonly schemaVersion: number
  readonly generatedBy: string
  readonly id: HorizonsMissionId
  readonly command: string
  readonly frame: Readonly<Record<string, string>>
  readonly coverage: { readonly firstJdTdb: number; readonly lastJdTdb: number }
  readonly dataStatusBoundary: Readonly<Record<string, string | number>>
  readonly samples: readonly HorizonsVectorSample[]
}
export const HORIZONS_TRAJECTORY_INDEX = {
  "voyager1": {
    "assetUrl": "/ephemerides/voyager1-e22aa97e021e13d7.json",
    "sha256": "e22aa97e021e13d7a3c630b317a46e86c397caf7c3994f44302d0df1b343c23d",
    "bytes": 148727,
    "sampleCount": 1118,
    "firstJdTdb": 2443394.5,
    "lastJdTdb": 2470184.5,
    "cadencesDays": [
      30,
      1,
      0.25
    ],
    "actualDataThrough": "2026-08-26",
    "predictionStarts": "2026-08-27",
    "predictionStartsJdTdb": 2461279.5
  },
  "voyager2": {
    "assetUrl": "/ephemerides/voyager2-e28376ffa0cb974f.json",
    "sha256": "e28376ffa0cb974f265b4efeef5187173efb73b804d5321756d2c8bc9e9f8c34",
    "bytes": 178870,
    "sampleCount": 1342,
    "firstJdTdb": 2443376.5,
    "lastJdTdb": 2470166.5,
    "cadencesDays": [
      30,
      1,
      0.25
    ],
    "actualDataThrough": "2026-08-26",
    "predictionStarts": "2026-08-27",
    "predictionStartsJdTdb": 2461279.5
  },
  "pioneer10": {
    "assetUrl": "/ephemerides/pioneer10-a9d0ea317ddecec0.json",
    "sha256": "a9d0ea317ddecec0425587eedae906b024b6424d9af861d7477334b68a0aa323",
    "bytes": 138113,
    "sampleCount": 1060,
    "firstJdTdb": 2441380.5,
    "lastJdTdb": 2469790.5,
    "cadencesDays": [
      30,
      1,
      0.25
    ],
    "actualDataThrough": "2003-01-23",
    "predictionStarts": "2003-01-24",
    "predictionStartsJdTdb": 2452663.5
  },
  "newhorizons": {
    "assetUrl": "/ephemerides/newhorizons-98e5435c1e00bc83.json",
    "sha256": "98e5435c1e00bc83d19952e7eee7bacf75fee5a727558fa5115a9590d482f577",
    "bytes": 116398,
    "sampleCount": 872,
    "firstJdTdb": 2453755.5,
    "lastJdTdb": 2469805.5,
    "cadencesDays": [
      30,
      1,
      0.25
    ],
    "actualDataThrough": "2026-08-26",
    "predictionStarts": "2026-08-27",
    "predictionStartsJdTdb": 2461279.5
  },
  "cassini": {
    "assetUrl": "/ephemerides/cassini-2226df1ba8a539e2.json",
    "sha256": "2226df1ba8a539e2747723a85fff42042c8567e7b9e3aa404b3868852bfb3b91",
    "bytes": 727809,
    "sampleCount": 5449,
    "firstJdTdb": 2450737.5,
    "lastJdTdb": 2458011.5,
    "cadencesDays": [
      30,
      1,
      0.25
    ],
    "actualDataThrough": "2017-09-15",
    "predictionStarts": "2017-09-16",
    "predictionStartsJdTdb": 2458012.5
  },
  "galileo": {
    "assetUrl": "/ephemerides/galileo-670db90f89a8f390.json",
    "sha256": "670db90f89a8f3905b2fbe5309ef5dfc298c66034d57492eeea9555f8da09e55",
    "bytes": 476893,
    "sampleCount": 3605,
    "firstJdTdb": 2447819.5,
    "lastJdTdb": 2452911.5,
    "cadencesDays": [
      30,
      1,
      0.25
    ],
    "actualDataThrough": "2003-09-21",
    "predictionStarts": "2003-09-22",
    "predictionStartsJdTdb": 2452904.5
  },
  "dawn": {
    "assetUrl": "/ephemerides/dawn-d44048176476ac5c.json",
    "sha256": "d44048176476ac5c2c78435a619bd1aa6e9420eeed64befd5f8d692b97bfc660",
    "bytes": 1492502,
    "sampleCount": 11258,
    "firstJdTdb": 2454371.5,
    "lastJdTdb": 2467550.5,
    "cadencesDays": [
      30,
      1,
      0.25
    ],
    "actualDataThrough": "2018-10-31",
    "predictionStarts": "2018-11-01",
    "predictionStartsJdTdb": 2458423.5
  },
  "rosetta": {
    "assetUrl": "/ephemerides/rosetta-7cf9802ba3aecd84.json",
    "sha256": "7cf9802ba3aecd84a7bb187f2804ee27385bce53d67aa273a5128b372f6a7a1d",
    "bytes": 228059,
    "sampleCount": 1706,
    "firstJdTdb": 2453067.5,
    "lastJdTdb": 2457665.5,
    "cadencesDays": [
      30,
      1,
      0.25
    ],
    "actualDataThrough": "2016-09-30",
    "predictionStarts": "2016-10-01",
    "predictionStartsJdTdb": 2457662.5
  },
  "osirisrex": {
    "assetUrl": "/ephemerides/osirisrex-3bad4c1b4a171338.json",
    "sha256": "3bad4c1b4a17133839edfc90bd80e22cee2c54cf4ae98073a92a24a48c8de411",
    "bytes": 255256,
    "sampleCount": 1910,
    "firstJdTdb": 2457640.5,
    "lastJdTdb": 2462581.5,
    "cadencesDays": [
      30,
      1,
      0.25
    ],
    "actualDataThrough": "2026-08-26",
    "predictionStarts": "2026-08-27",
    "predictionStartsJdTdb": 2461279.5
  },
  "lucy": {
    "assetUrl": "/ephemerides/lucy-f3a0f2496d3d048b.json",
    "sha256": "f3a0f2496d3d048bf85f7e989db55eee286aabd5e84e33417f411b5899de55dd",
    "bytes": 159926,
    "sampleCount": 1190,
    "firstJdTdb": 2459504.5,
    "lastJdTdb": 2463688.5,
    "cadencesDays": [
      30,
      1,
      0.25
    ],
    "actualDataThrough": "2026-08-26",
    "predictionStarts": "2026-08-27",
    "predictionStartsJdTdb": 2461279.5
  },
  "psyche": {
    "assetUrl": "/ephemerides/psyche-5d2d12ff51345b9b.json",
    "sha256": "5d2d12ff51345b9b7d53eeb59656f461f0b7f5bb22561b3714bbbd8c6e34ed87",
    "bytes": 24339,
    "sampleCount": 177,
    "firstJdTdb": 2460231.5,
    "lastJdTdb": 2462151.5,
    "cadencesDays": [
      30,
      1,
      0.25
    ],
    "actualDataThrough": "2026-08-26",
    "predictionStarts": "2026-08-27",
    "predictionStartsJdTdb": 2461279.5
  },
  "europaclipper": {
    "assetUrl": "/ephemerides/europaclipper-57e7ecd7d01cdbad.json",
    "sha256": "57e7ecd7d01cdbade0fea27b0850689292070b84f5f91dcbb55ee2aa3187188b",
    "bytes": 264430,
    "sampleCount": 1989,
    "firstJdTdb": 2460598.5,
    "lastJdTdb": 2464207.5,
    "cadencesDays": [
      30,
      1,
      0.25
    ],
    "actualDataThrough": "2026-08-26",
    "predictionStarts": "2026-08-27",
    "predictionStartsJdTdb": 2461279.5
  }
} as const
